# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-05 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('number_of_votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VotingPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField()),
                ('option_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_one', to='polls.Option')),
                ('option_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_two', to='polls.Option')),
            ],
        ),
    ]
